### ISSUE TITLE
在修改器终结者附加终极修改器时，谁笑到最后卡片限制异常

### ISSUE THREAD

**Issue by 63enjoy** [Lazuplis-Mei/MemToExe#2]
在修改器终结者附加终极修改器时，谁笑到最后卡片限制异常，不论是直接修改还是保存都无法正常修改。用od保存修改正常

**Comment by Lazuplis-Mei** [comment]
修改器终结者本身就不是一个稳定的程序，你可以尝试手动添加项目，而不是依赖拦截，反正终极修改器是开源的。我已经永久停止对修改器终结者的支持
